language: perl

perl:
    - "dev"
    - "dev-thr-mb-shrplib-dbg"
    - "5.24"
    - "5.24-extras"
    - "5.24-thr-mb-shrplib-dbg"
    - "5.22"
    - "5.22-extras"
    - "5.20"
    - "5.20-extras"
    - "5.18"
    - "5.18-extras"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

sudo: false             # faster builds as long as you don't need sudo access

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command

install:
    - cpan-install --deps       # installs prereqs, including recommends
    - cpanm Test::Pod Test::Pod::Coverage || true
    - cpanm Test::Portability::Files || true

matrix:
  fast_finish: true
  allow_failures:
    - perl: dev
    - perl: dev-thr-mb-shrplib-dbg

notifications:
    irc: "irc.perl.org#nytprof"
