--- #YAML:1.0
name:               Devel-NYTProf
version:            2.07
abstract:           Powerful feature-rich perl source code profiler
author:
    - Adam Kaplan <akaplan@cpan.org>, Tim Bunce <timb@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:  0
    List::Util:    0
    Test::More:    0
    XSLoader:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
