--- #YAML:1.0
name:                Devel-NYTProf
version:             2.07
abstract:            Powerful feature-rich perl source code profiler
license:             perl
author:              
    - Adam Kaplan <akaplan@cpan.org>, Tim Bunce <timb@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Getopt::Long:                  0
    List::Util:                    0
    Test::More:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
