---
abstract: 'Powerful fast feature-rich Perl source code profiler'
author:
  - 'Tim Bunce <timb@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-NYTProf
no_index:
  directory:
    - t
    - inc
  package:
    - SVG
resources:
  MailingList: http://groups.google.com/group/develnytprof-dev
  bugtracker: https://github.com/timbunce/devel-nytprof/issues
  homepage: https://code.google.com/p/perl-devel-nytprof/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/timbunce/devel-nytprof.git
version: '5.07'
