--- #YAML:1.0
name:                Devel-NYTProf
version:             0.09
abstract:            Perl line profiler with advanced reporting
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.17
distribution_type:   module
requires:     
    Getopt::Long:         0
