--- #YAML:1.0
name:                Devel-NYTProf
version:             1.11
abstract:            line-by-line code profiler and report generator
license:             perl
author:              
    - Adam Kaplan <akaplan@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Getopt::Long:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
